name: Test
port: 3031
host: 0.0.0.0
db: db.json
statics: public/

auth:
#   jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
#   jwtExpire: 3600
#   unauthorizedStatusCode: 403
#   urlSkip:
#     - /images/:
#        method: get
#     - /contact/register:
#        method: post
#      - /products/{*}:
#        method: get
